### ISSUE TITLE
Bug Report: timer is always on top during break time

### ISSUE THREAD

**Issue by hunkjazz** [roldanjrCodeArts9711/productivity-timer#105]
**Describe the bug**
Timer is always on top of other windows, during break time. Even though, I disabled it.

**To Reproduce**
1. Toggle "always on top" to disable it;
2. Start break time;
3. Try to use computer, during break time;
4. It's barely possible. Timer window is always on top.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 32 Workstation
 - App Version: PRODUCTIVITY-TIMER-v3.0.0-linux.rpm

**Comment by roldanjrCodeArts9711** [comment]
When `Fullscreen Break` is enabled by default. 
The app will be set `Always on top` to `true` when break started. 
It will make sense because if it will not be on top, users who want to discipline their selves will likely to continue to work even though it is time to take a break.  

Even if you disabled `Always on top` featured but didn't disable `Fullscreen Break` it will forcefully be on top of other apps.
But after the break finished, the app will follow again the users settings.

It you did not like it, just disabled `Fullscreen Break`.

**Comment by hunkjazz** [comment]
You're right!
