### ISSUE TITLE
Dev keys grabbed/registered in Production build

### ISSUE THREAD

**Issue by beefy-raccoon** [roldanjrCodeArts9711/productivity-timer#58]
Hey there,

I'm on Windows using WSL and it took me a while to figure out why I can't use CTRL-R in bash anymore. The culprit seems to be productivity timer (found out via VS tool spyxx).

I suspect the function `registerGlobalShortcut` (https://github.com/roldanjrCodeArts9711/productivity-timer/blob/dc00c43dab3b72ce3295bd995b1318978c23bdd7/app/public/electron.js#L81) and propose to construct the `shortcutKeys` array in a different way: merge production with dev for dev builds. Right now it seems to grab keys unnecessarily with empty callbacks.

Hope you can fix and re-release soon, would love to use the app afterwards again.
Cheers!

**Comment by roldanjrCodeArts9711** [comment]
@beefy-raccoon yes you are correct 👍. It happened maybe because I disabled the `CTRL+R` on production build of the app and it seems like it is being disabled while the productivity-timer is still running on the background. 

I will try to make or find another way to prevent that from happening again.
Maybe on my version 2 I will fix that.

![image](https://user-images.githubusercontent.com/38913069/76534204-22dcad80-64b4-11ea-8fbe-32bbe6923086.png)

**Comment by sekwah41** [comment]
You should only be registering permanently global key-binds that are specific for your application e.g. ctrl + shift + s to show. As the other ones are only effecting your program when you have focus you should register and remove them on focus and blur. I have suggested a fix for this in another issue which has the same problem.

**Comment by roldanjrCodeArts9711** [comment]
> You should only be registering permanently global key-binds that are specific for your application e.g. ctrl + shift + s to show. As the other ones are only effecting your program when you have focus you should register and remove them on focus and blur. I have suggested a fix for this in another issue which has the same problem.

@sekwah41 yes, you're actually right. That was the thing that I did not realize when I first created the app due to the facts that I created it with my own personal preferences and not concern about other users who are using it. 

Now I'm currently working and rebuilding the app with my spare time that address all these issues here on Github.
I'm actually rebuilding it from scratch using `Typescript` cause I don't like to mess up with my old `Javascript` code and make it very useful to everybody and optimize as much as possible.

Currently I'm done with the built-in task list and I'm working again with other new cool features that might help as well. 

![image](https://user-images.githubusercontent.com/38913069/79834742-2ed75b80-83e0-11ea-8104-3c9d2e2fa89f.png)
