### ISSUE TITLE
Full screen feature

### ISSUE THREAD

**Issue by jedsonmelo** [roldanjrCodeArts9711/productivity-timer#66]
**Is your feature request related to a problem? Please describe.**
not

**Describe the solution you'd like**
Full screen feature was removed on beta version, but this feature are very helpful to me because help with the concentration

**Describe alternatives you've considered**
that feature could be disable for default

**Comment by roldanjrCodeArts9711** [comment]
> **Is your feature request related to a problem? Please describe.**
> not
> 
> **Describe the solution you'd like**
> Full screen feature was removed on beta version, but this feature are very helpful to me because help with the concentration
> 
> **Describe alternatives you've considered**
> that feature could be disable for default

I'm sorry about that @jedsonmelo. I'm very busy lately and had no time to write proper documentation of the apps new features and changes.

`Fullscreen Feature` is being moved to `Strict Mode Feature` due to some users request.

I already updated `README.md` for some overview of changes and new features of the app.
Please read it if you have time. Thank you for your patience. Good day!

**Comment by jedsonmelo** [comment]
I understend. Thanks for the amazing app.

**Comment by Hydro8** [comment]
Hi

What was the old way to handle this ?

I like the strict mode to have the fullscreen when it's tile to take a break but I also need to be able to interrupt timer if I'm away for x minutes.
