### ISSUE TITLE
Package.json possible issues

### ISSUE THREAD

**Issue by sekwah41** [roldanjrCodeArts9711/productivity-timer#90]
Ive not followed the thing as it's not too much a bug but more a request. I was just going over the package.json and there seems to be missing information such as the electron version.

Also, I am not too experienced with yarn, but there seems to be a mix of both in the package file for the launch scripts though the main issue seemed to be only the fact electron didn't install itself though I can't see Electron in the devDependencies. After adding, it seems to be okay.

**Comment by roldanjrCodeArts9711** [comment]
You can find `electron` as devDependencies inside `app/package.json`.

The root `package.json` is only calling the scripts inside the app folder so that running and building the app doesn't always required you to do such `cd app/` and run some of the scripts.

Also, in order to call the scripts inside the sub-folder I used npm `--prefix` flag.

**Comment by sekwah41** [comment]
Ah thats a first, usually projects only have everything setup from the main folder though I assume you've got it set up like that to position the node_modules differently?
