### ISSUE TITLE
Unable to dowload from the snap store and not able to find the app upon installing as .deb file

### ISSUE THREAD

**Issue by Xanaxus** [roldanjrCodeArts9711/productivity-timer#97]

**Comment by roldanjrCodeArts9711** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - App Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
